### ISSUE TITLE
Creating endpoint

### ISSUE THREAD

**Issue by MathusanP** [Criticalcarpet/kek-status#1]
Need to make an endpoint between heroku and uptime robot, please feel free to leave suggestions :p

**Comment by Criticalcarpet** [comment]
@bagelwastaken Umm.... Can I help you in that ? 

Shall I open a PR in kekbot repo ?

**Comment by MathusanP** [comment]
> @bagelwastaken Umm.... Can I help you in that ? 
> 
> Shall I open a PR in kekbot repo ?

Feel free to, but make sure to follow pr guidelines!
